### ISSUE TITLE
Add obj attribute to require permission to support django item based permissions API

### ISSUE THREAD

**Issue by LilithWittmann** [serioeseGmbH/serious-django-services#2]
In some projects we want to use the item based permissions concept of django inside a service. Therefore it would be cool if we could do the same as django: provide the option to have an object as an attribute of the require_permission method. (see https://docs.djangoproject.com/en/2.1/ref/contrib/auth/#django.contrib.auth.models.User.has_perm)

**Comment by cobalamin** [comment]
Closed in PR #3
